// <auto-generated />
using System;
using FastRegistrator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastRegistrator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220822133630_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FastRegistrator.ApplicationCore.Domain.Entities.Error", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Error");
                });

            modelBuilder.Entity("FastRegistrator.ApplicationCore.Domain.Entities.PersonData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonData");
                });

            modelBuilder.Entity("FastRegistrator.ApplicationCore.Domain.Entities.PrizmaCheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrizmaResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RejectionReasonCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PrizmaChecks");
                });

            modelBuilder.Entity("FastRegistrator.ApplicationCore.Domain.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("FastRegistrator.ApplicationCore.Domain.Entities.StatusHistoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusDT")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("StatusHistory");
                });

            modelBuilder.Entity("FastRegistrator.ApplicationCore.Domain.Entities.Error", b =>
                {
                    b.HasOne("FastRegistrator.ApplicationCore.Domain.Entities.Registration", null)
                        .WithOne("Error")
                        .HasForeignKey("FastRegistrator.ApplicationCore.Domain.Entities.Error", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastRegistrator.ApplicationCore.Domain.Entities.PersonData", b =>
                {
                    b.HasOne("FastRegistrator.ApplicationCore.Domain.Entities.Registration", null)
                        .WithOne("PersonData")
                        .HasForeignKey("FastRegistrator.ApplicationCore.Domain.Entities.PersonData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FastRegistrator.ApplicationCore.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PersonDataId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PersonDataId");

                            b1.ToTable("PersonData");

                            b1.WithOwner()
                                .HasForeignKey("PersonDataId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("FastRegistrator.ApplicationCore.Domain.Entities.PrizmaCheckResult", b =>
                {
                    b.HasOne("FastRegistrator.ApplicationCore.Domain.Entities.Registration", null)
                        .WithOne("PrizmaCheckResult")
                        .HasForeignKey("FastRegistrator.ApplicationCore.Domain.Entities.PrizmaCheckResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastRegistrator.ApplicationCore.Domain.Entities.StatusHistoryItem", b =>
                {
                    b.HasOne("FastRegistrator.ApplicationCore.Domain.Entities.Registration", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("RegistrationId");
                });

            modelBuilder.Entity("FastRegistrator.ApplicationCore.Domain.Entities.Registration", b =>
                {
                    b.Navigation("Error");

                    b.Navigation("PersonData")
                        .IsRequired();

                    b.Navigation("PrizmaCheckResult");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
